name: elephantslab_test
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 0.17.3+1
  cupertino_icons: ^0.1.3
  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/bitcoin.png
    - assets/images/ethereum.png
    - assets/images/ripple.png
  fonts:
    - family: ElephantsIcons
      fonts:
        - asset: assets/customIconsFont/ElephantsIcons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
